apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcks
spec:
  # Add fields here
  name: microcks
  version: "latest"
  microcks: 
    replicas: 1
    url: microcks.192.168.64.7.nip.io
    ingressAnnotations:
      cert-manager.io/cluster-issuer: self-signed-issuer
      my-annotation: my-value
    generateCert: false
  postman:
    replicas: 1
  keycloak:
    install: true
    persistent: true
    volumeSize: 1Gi
    url: keycloak-microcks.192.168.64.7.nip.io
    privateUrl: http://microcks-keycloak.microcks.svc.cluster.local:8080
    ingressAnnotations:
      cert-manager.io/cluster-issuer: self-signed-issuer
      my-annotation: my-value
    generateCert: false
    serviceAccount: microcks-serviceaccount
    serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi

