apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcks
spec:
  # Add fields here
  name: microcks
  version: "latest"
  microcks: 
    replicas: 1
  postman:
    replicas: 1
  keycloak:
    install: false
    url: keycloak.microcks-labs.apps.cluster-6282.6282.sandbox1686.opentlc.com
    realm: microcks
    privateUrl: http://keycloak.microcks-labs.svc.cluster.local:8080/auth
    serviceAccount: microcks-serviceaccount
    serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi
    replicas: 1
  features:
    repositoryFilter:
      enabled: true
      labelKey: domain
      labelLabel: Domain
      labelList: domain,status
    async:
      enabled: true
      defaultBinding: KAFKA
      defaultFrequency: 3
      kafka:
        install: true