---
# defaults specification file for microcks installation
name: microcks
version: "1.0.0"
microcks: 
  replicas: 1
  #url: microcks.192.168.99.100.nip.io
  #ingress_annotations:
    #cert-manager.io/issuer: my-cert-issuer
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/ingress.class: nginx
  generate_cert: true
  resources:
    #equests:
      #cpu: 250m
      #memory: 400Mi
    limits:
      #cpu: 500m
      memory: 512Mi
  #log_level: TRACE | DEBUG | INFO | WARN
  log_level: INFO
postman:
  replicas: 1
keycloak:
  install: true
  realm: microcks
  persistent: true
  volume_size: 1Gi
  #url: keycloak.192.168.99.100.nip.io
  #url: http://microcks-keycloak:8080
  #public_url: https://keycloak-microcks.192.168.64.6.nip.io/auth
  #ingress_annotations:
    #cert-manager.io/issuer: my-cert-issuer
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/ingress.class: nginx
  generate_cert: true
  service_account: microcks-serviceaccount
  service_account_credentials: ab54d329-e435-41ae-a900-ec6b3fe15c54
mongodb:
  install: true
  persistent: true
  volume_size: 2Gi
features:
  repository_filter:
    enabled: false
    label_key: domain
    label_label: Domain
    label_list: domain,status
  async:
    enabled: false
    default_binding: KAFKA
    default_frequency: 10
    default_avro_encoding: RAW
    kafka:
      install: true
      #url: 192.168.99.100.nip.io
      persistent: false
      volume_size: 2Gi
      resources:
        #requests:
          #cpu: 100m
          #memory: 256Mi
        limits:
          #cpu: 500m
          memory: 800Mi
      zk_resources:
        #requests:
          #cpu: 100m
          #memory: 256Mi
        limits:
          #cpu: 500m
          memory: 800Mi
      schema_registry:
        #url: https://schema-registry.192.168.99.100.nip.io
        confluent: true
        #username: microcks
        credentials_source: USER_INFO

    mqtt:
      #url:
      username: microcks
      password: microcks