---
# defaults specification file for microcks installation
name: microcks
version: "0.9.0"
microcks: 
  replicas: 2
  #url: microcks.192.168.99.100.nip.io
postman:
  replicas: 2
keycloak:
  install: true
  persistent: true
  volume_size: 1Gi
  #url: keycloak.192.168.99.100.nip.io
  replicas: 1
mongodb:
  install: true
  persistent: true
  volume_size: 2Gi
  replicas: 1
features:
  repository_filter:
    enabled: false
    label_key: domain
    label_label: Domain
    label_list: domain,status