kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: "{{name}}-kafka"
  namespace: '{{ meta.namespace }}'
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: '2.7'
      inter.broker.protocol.version: '2.7'
    version: 2.7.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        tls: true
        {% if 'url' not in features.async.kafka and 'route.openshift.io' in api_groups %}

        type: route
        {% endif %}
        
        {% if 'url' in features.async.kafka and 'route.openshift.io' not in api_groups %}
        
        type: ingress
        configuration:
          bootstrap:
            host: "{{name}}-kafka.{{features.async.kafka.url}}"
          brokers:
          - broker: 0
            host: "{{name}}-kafka-0.{{features.async.kafka.url}}"
        {% endif %}
    replicas: 1
    storage:
      type: ephemeral
    resources:
      {{ features.async.kafka.resources | to_nice_yaml(indent=2) | trim | indent(6) }}
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    resources:
      {{ features.async.kafka.zk_resources | to_nice_yaml(indent=2) | indent(6) }}