kind: Ingress
apiVersion: extensions/v1
metadata:
  name: "{{name}}-keycloak"
  namespace: '{{ meta.namespace }}'
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    {% if current_cr.spec.keycloak.ingressAnnotations is defined -%}
    {% for key in current_cr.spec.keycloak.ingressAnnotations.keys() -%}
    {{ key }}: {{ current_cr.spec.keycloak.ingressAnnotations[key] }}
    {% endfor %}
    {% endif %}
    
  labels:
    app: "{{name}}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{keycloak.url}}"
    secretName: {{keycloak.ingress_secret_ref|default(name ~ "-keycloak-ingress-secret")}}
  rules:
  - host: "{{keycloak.url}}"
    http:
      paths:
      - backend:
          serviceName: "{{name}}-keycloak"
          servicePort: 8080