kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "{{name}}-keycloak"
  namespace: '{{ meta.namespace }}'
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: "{{name}}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{keycloak.url}}"
    secretName: {{keycloak.ingress_secret_ref|default(name ~ "-keycloak-ingress-secret")}}
  rules:
  - host: "{{keycloak.url}}"
    http:
      paths:
      - backend:
          serviceName: "{{name}}-keycloak"
          servicePort: 8080