kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "{{name}}"
  namespace: '{{ meta.namespace }}'
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    {% if current_cr.spec.microcks.ingressAnnotations is defined -%}
    {% for key in current_cr.spec.microcks.ingressAnnotations.keys() -%}
    {{ key }}: {{ current_cr.spec.microcks.ingressAnnotations[key] }}
    {% endfor %}
    {% endif %}

  labels:
    app: "{{name}}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{microcks.url}}"
    secretName: {{microcks.ingress_secret_ref|default(name ~ "-microcks-ingress-secret")}}
  rules:
  - host: "{{microcks.url}}"
    http:
      paths:
      - backend:
          serviceName: "{{name}}"
          servicePort: 8080