kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{name}}-grpc"
  namespace: '{{ meta.namespace }}'
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {% if current_cr.spec.microcks.grpcIngressAnnotations is defined -%}
    {% for key in current_cr.spec.microcks.grpcIngressAnnotations.keys() -%}
    {{ key }}: {{ current_cr.spec.microcks.grpcIngressAnnotations[key] }}
    {% endfor %}
    {% endif %}
    
  labels:
    app: "{{name}}"
    group: microcks
spec:
  tls:
  - hosts:
    #- "{{microcks.url|regex_replace('^('~(name|regex_escape())~')(.*)','\\1-grpc\\2')}}"
    - "{{microcks.url|regex_replace('^([^.-]+)(.*)','\\1-grpc\\2')}}"
  rules:
  - host: "{{microcks.url|regex_replace('^([^.-]+)(.*)','\\1-grpc\\2')}}"
    #host: "{{microcks.url|regex_replace('^('~(name|regex_escape())~')(.*)','\\1-grpc\\2')}}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{name}}-grpc"
            port: 
              number: 9090