apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcks
spec:
  # Add fields here
  name: microcks
  version: "nightly"
  microcks: 
    replicas: 1
    url: microcks-op.192.168.64.6.nip.io
    ingressSecretRef: my-secret-for-microcks-ingress
  postman:
    replicas: 1
  keycloak:
    install: true
    persistent: true
    volumeSize: 1Gi
    url: keycloak-op.192.168.64.6.nip.io
    ingressSecretRef: my-secret-for-keycloak-ingress
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi