name: build-verify-package
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
jobs:
  build-verify-package:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Package container image for operator e2e tests
        run: |
          docker build -f build/Dockerfile -t quay.io/microcks-ansible-operator:e2e-tests .
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
          docker push quay.io/microcks/microcks-ansible-operator:e2e-tests

      - name: Install kubectl and Kind Cluster
        run: |
          set -x
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
            && sudo mv ./kubectl /usr/local/bin/kubectl \
            && sudo chmod +x /usr/local/bin/kubectl
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64 \
            && sudo mv ./kind /usr/local/bin/kind \
            && sudo chmod +x /usr/local/bin/kind
            
      - name: Run e2e tests on operator using Kuttl.dev
        run: |
          set -x
          curl -Lo ./kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.11.1/kubectl-kuttl_0.11.1_linux_x86_64 \
            && sudo cp kuttl /usr/local/bin/kubectl-kuttl \
            && sudo chmod +x /usr/local/bin/kubectl-kuttl
          kubectl kuttl test --config=./tests/kuttl-test.yaml

      - name: Set environment for branch
        run: |
          set -x
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "IMAGE_TAG=nightly" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REF == "refs/tags/$GITHUB_REF_NAME" ]]; then
            echo "IMAGE_TAG=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          fi

      - name: Tag container image
        if: github.repository_owner == 'microcks'
        run: |
          docker tag quay.io/microcks/microcks-ansible-operator:e2e-tests quay.io/microcks/microcks-ansible-operator:$IMAGE_TAG

      - name: Login and push to Quay.io Registry
        if: github.repository_owner == 'microcks'
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
          docker push quay.io/microcks/microcks-ansible-operator:$IMAGE_TAG